package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/simanadler/llm-d-edge/model-manager/pkg/installer"
	"github.com/simanadler/llm-d-edge/model-manager/pkg/types"
	"gopkg.in/yaml.v3"
)

// ModelYAMLConfig represents the YAML structure for installed models
type ModelYAMLConfig struct {
	Edge EdgeYAMLConfig `yaml:"edge"`
}

// EdgeYAMLConfig contains the edge configuration for installed models
type EdgeYAMLConfig struct {
	Models ModelsYAMLConfig `yaml:"models"`
}

// ModelsYAMLConfig contains local model configurations
type ModelsYAMLConfig struct {
	Local []LocalModelYAML `yaml:"local"`
}

// LocalModelYAML represents a local model with full capabilities
type LocalModelYAML struct {
	Name          string                 `yaml:"name"`
	Format        string                 `yaml:"format"`
	Quantization  string                 `yaml:"quantization"`
	Priority      int                    `yaml:"priority"`
	Path          string                 `yaml:"path,omitempty"`
	Capabilities  *ModelCapabilities     `yaml:"capabilities,omitempty"`
	Matching      *ModelMatching         `yaml:"matching,omitempty"`
}

// ModelCapabilities represents model capabilities
type ModelCapabilities struct {
	ParameterCount string             `yaml:"parameter_count,omitempty"`
	ContextLength  int                `yaml:"context_length,omitempty"`
	ModelFamily    string             `yaml:"model_family,omitempty"`
	QualityTier    string             `yaml:"quality_tier,omitempty"`
	Tasks          map[string]float64 `yaml:"tasks,omitempty"`
	Domains        map[string]float64 `yaml:"domains,omitempty"`
}

// ModelMatching represents model matching rules
type ModelMatching struct {
	CanSubstitute   []PatternRule `yaml:"can_substitute,omitempty"`
	ExcludePatterns []string      `yaml:"exclude_patterns,omitempty"`
}

// PatternRule represents a pattern matching rule
type PatternRule struct {
	Pattern string `yaml:"pattern"`
}

// YAMLGenerator generates YAML configuration for installed models
type YAMLGenerator struct {
	modelsDir  string
	outputPath string
}

// NewYAMLGenerator creates a new YAML generator
func NewYAMLGenerator(modelsDir, outputPath string) *YAMLGenerator {
	if modelsDir == "" {
		home, _ := os.UserHomeDir()
		modelsDir = getDefaultModelsDir(home)
	}
	
	if outputPath == "" {
		// Default to models directory
		outputPath = filepath.Join(filepath.Dir(modelsDir), "installed-models.yaml")
	}
	
	return &YAMLGenerator{
		modelsDir:  modelsDir,
		outputPath: outputPath,
	}
}

// GenerateYAML generates YAML configuration for all installed models
func (g *YAMLGenerator) GenerateYAML() error {
	// Get list of installed models
	modelInstaller := installer.NewModelInstaller(g.modelsDir)
	installed, err := modelInstaller.ListInstalled()
	if err != nil {
		return fmt.Errorf("failed to list installed models: %w", err)
	}

	// Build YAML configuration
	config := ModelYAMLConfig{
		Edge: EdgeYAMLConfig{
			Models: ModelsYAMLConfig{
				Local: make([]LocalModelYAML, 0, len(installed)),
			},
		},
	}

	for i, inst := range installed {
		localModel := g.convertToLocalModelYAML(inst, i+1)
		config.Edge.Models.Local = append(config.Edge.Models.Local, localModel)
	}

	// Marshal to YAML with custom formatting
	data, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}

	// Add header comment
	header := `# llm-d Edge Router - Installed Models Configuration
# This file is automatically generated by model-manager
# Copy the models you want to use into your edge-router config.yaml
#
# Structure matches edge-router/config.with-model-matching.yaml
# You can customize capabilities and matching rules as needed

`
	fullContent := header + string(data) + "\n# Made with Bob\n"

	// Ensure directory exists
	dir := filepath.Dir(g.outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Write to file
	if err := os.WriteFile(g.outputPath, []byte(fullContent), 0644); err != nil {
		return fmt.Errorf("failed to write YAML file: %w", err)
	}

	return nil
}

// convertToLocalModelYAML converts an installed model to YAML format
func (g *YAMLGenerator) convertToLocalModelYAML(inst installer.InstalledModel, priority int) LocalModelYAML {
	model := LocalModelYAML{
		Name:     inst.Model.Name,
		Priority: priority,
		Path:     inst.InstallPath,
	}

	// Detect format and quantization from path or metadata
	format, quant := g.detectFormatAndQuantization(inst)
	model.Format = format
	model.Quantization = quant

	// Add capabilities if available
	if inst.Model.ParameterCount != "" && inst.Model.ParameterCount != "unknown" {
		model.Capabilities = &ModelCapabilities{
			ParameterCount: inst.Model.ParameterCount,
			ContextLength:  inst.Model.ContextLength,
			ModelFamily:    inst.Model.ModelFamily,
			QualityTier:    inst.Model.QualityTier,
		}

		// Add task capabilities if available
		if len(inst.Model.Tasks) > 0 {
			model.Capabilities.Tasks = inst.Model.Tasks
		}

		// Add domain expertise if available
		if len(inst.Model.Domains) > 0 {
			model.Capabilities.Domains = inst.Model.Domains
		}
	}

	// Add matching rules based on model characteristics
	model.Matching = g.generateMatchingRules(inst.Model)

	return model
}

// detectFormatAndQuantization detects format and quantization from installation
func (g *YAMLGenerator) detectFormatAndQuantization(inst installer.InstalledModel) (string, string) {
	format := "gguf"      // Default
	quantization := "4bit" // Default

	// Check for MLX format
	if g.hasMLXFiles(inst.InstallPath) {
		format = "mlx"
	}

	// Try to detect quantization from path or files
	pathLower := strings.ToLower(inst.InstallPath)
	if strings.Contains(pathLower, "q8") || strings.Contains(pathLower, "8bit") {
		quantization = "8bit"
	} else if strings.Contains(pathLower, "q4") || strings.Contains(pathLower, "4bit") {
		quantization = "4bit"
	} else if strings.Contains(pathLower, "fp16") || strings.Contains(pathLower, "16bit") {
		quantization = "fp16"
	}

	return format, quantization
}

// hasMLXFiles checks if directory contains MLX format files
func (g *YAMLGenerator) hasMLXFiles(dir string) bool {
	mlxFiles := []string{"weights.npz", "config.json"}
	for _, file := range mlxFiles {
		if _, err := os.Stat(filepath.Join(dir, file)); err == nil {
			return true
		}
	}
	return false
}

// generateMatchingRules generates matching rules based on model metadata
func (g *YAMLGenerator) generateMatchingRules(model types.ModelMetadata) *ModelMatching {
	matching := &ModelMatching{
		CanSubstitute:   make([]PatternRule, 0),
		ExcludePatterns: make([]string, 0),
	}

	// Generate substitution patterns based on parameter count
	paramCount := strings.ToLower(strings.TrimSuffix(model.ParameterCount, "B"))
	if paramCount != "" && paramCount != "unknown" {
		// Can substitute for similar sized models
		matching.CanSubstitute = append(matching.CanSubstitute,
			PatternRule{Pattern: fmt.Sprintf("*%s*", paramCount)},
		)
	}

	// Add model family patterns
	if model.ModelFamily != "" && model.ModelFamily != "unknown" {
		matching.CanSubstitute = append(matching.CanSubstitute,
			PatternRule{Pattern: fmt.Sprintf("%s*", model.ModelFamily)},
		)
	}

	// Add exclusion patterns for much larger models
	if paramCount != "" && paramCount != "unknown" {
		// Exclude models that are significantly larger
		largerSizes := getLargerModelSizes(paramCount)
		for _, size := range largerSizes {
			matching.ExcludePatterns = append(matching.ExcludePatterns,
				fmt.Sprintf("*%s*", size),
			)
		}
	}

	// Always exclude premium models if this is not premium
	if model.QualityTier != "premium" {
		matching.ExcludePatterns = append(matching.ExcludePatterns,
			"gpt-4*",
			"claude-3-opus*",
			"claude-3.5-sonnet*",
		)
	}

	return matching
}

// getLargerModelSizes returns model sizes that are significantly larger
func getLargerModelSizes(currentSize string) []string {
	sizeOrder := []string{"0.5b", "1b", "3b", "7b", "8b", "13b", "14b", "30b", "32b", "70b", "72b"}
	
	// Find current position
	currentIdx := -1
	for i, size := range sizeOrder {
		if strings.Contains(size, currentSize) {
			currentIdx = i
			break
		}
	}

	if currentIdx == -1 {
		return []string{}
	}

	// Return sizes that are 2+ steps larger
	larger := make([]string, 0)
	for i := currentIdx + 2; i < len(sizeOrder); i++ {
		larger = append(larger, sizeOrder[i])
	}

	return larger
}

// GetOutputPath returns the output path for the generated YAML
func (g *YAMLGenerator) GetOutputPath() string {
	return g.outputPath
}

// Made with Bob